platform :ios, '8.0'

target "SloppySwiperExample" do
  pod "SloppySwiper", :path => "../"
end

# Uncomment the following lines to add testing dependencies
# target "DemoTests" do
#   pod 'Expecta'
# end

